import Head from 'next/head'
import Link from 'next/link'
import { FaTwitterSquare, FaInstagramSquare, FaLinkedin, FaFacebookSquare } from 'react-icons/fa'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Timothy Olili&#39;s Portifolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="text-center">

      <div className=" text-center mt-40">
        <h1 className='text-7xl text-blue-500'>
          Portfolio is Under Construction
        </h1>
      </div>

      <footer className=' mt-10 flex justify-center '>
        <Link  classNam=" flex shrink" href="https://www.linkedin.com/in/timothy-olili-2359b8176/">
          <a className='text-4xl p-4'>
          <FaLinkedin />
          </a>
        </Link>
        <Link  classNam=" flex shrink " href="https://twitter.com/Thy_Minimalist">
            <a className='text-4xl p-4'>
            <FaTwitterSquare />
            </a>
        </Link>
        
        <Link  classNam=" flex shrink" href="https://www.instagram.com/thy_olili/">
          <a className='text-4xl p-4'>
          <FaInstagramSquare />
          </a>
        </Link>

        <Link  classNam=" flex shrink" href="https://www.facebook.com/timothy.eric.96/">
          <a className='text-4xl p-4'>
            <FaFacebookSquare />
          </a>
        </Link>
      </footer>

      </main>
      
    </div>
  )
}
